# Generated by Django 5.2.1 on 2025-05-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_image/')),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=30)),
            ],
        ),
    ]
