# Generated by Django 5.2.1 on 2025-05-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_short_disc_blog_short_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_desc',
            field=models.CharField(default='', max_length=400),
        ),
    ]
