# Generated by Django 5.2.1 on 2025-05-26 13:05

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_disc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='subtitle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
