# Generated by Django 5.2.1 on 2025-05-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog_short_disc_alter_blog_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='short_disc',
            new_name='short_desc',
        ),
    ]
